// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgeoS0Lzh9TbqyOoAYeuXTJvu9tf4wt00',
    appId: '1:404205896026:web:4ed1b9c17c91d04daeb363',
    messagingSenderId: '404205896026',
    projectId: 'cafesharing-e6297',
    authDomain: 'cafesharing-e6297.firebaseapp.com',
    storageBucket: 'cafesharing-e6297.appspot.com',
    measurementId: 'G-PLV1GJTP72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXqCjfhHQQ9WF9wKmdhb1HnONv2W4HHEQ',
    appId: '1:404205896026:android:8d1fafde63b6ad21aeb363',
    messagingSenderId: '404205896026',
    projectId: 'cafesharing-e6297',
    storageBucket: 'cafesharing-e6297.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuUyu0sFh8q1arObQT7ga76JHTSFx1OHk',
    appId: '1:404205896026:ios:8f635659b750889faeb363',
    messagingSenderId: '404205896026',
    projectId: 'cafesharing-e6297',
    storageBucket: 'cafesharing-e6297.appspot.com',
    iosClientId: '404205896026-5hf1ukm8146p6i236aruip5vrem76s3r.apps.googleusercontent.com',
    iosBundleId: 'com.lim1t.cafesharing',
  );
}
